import { 
  FileText, Folder, BookOpen, Settings, Calendar, Inbox, 
  Target, Award, Briefcase, Lightbulb, Compass,
  Code, Database, Terminal, Heart, Star, Smile, Sparkles,
  MapPin, Mail, Link, Lock, Bell, Home, Activity, 
  BarChart2, CheckSquare, Coffee, Globe, Image, Music, 
  Film, Gift, Sun, Moon, Cloud, Umbrella, ShoppingCart, 
  Tag, Key, Scroll, Atom, Footprints, Dna, Brain,
  Book, Feather, Utensils, Shirt, Archive, Rocket, UsersRound, CircleCheck, Flag
} from 'lucide-svelte';

export const CURATED_ICONS = [
  { name: 'file-text', component: FileText, label: 'Document' },
  { name: 'folder', component: Folder, label: 'Folder' },
  { name: 'book-open', component: BookOpen, label: 'Book Open' },
  { name: 'book', component: Book, label: 'Book' },
  { name: 'scroll', component: Scroll, label: 'Philosophy / Scroll' },
  { name: 'brain', component: Brain, label: 'Psychology / Brain' },
  { name: 'feather', component: Feather, label: 'Poetry / Feather' },
  { name: 'atom', component: Atom, label: 'Science / Atom' },
  { name: 'dna', component: Dna, label: 'Gene / DNA' },
  { name: 'footprints', component: Footprints, label: 'Evolution / Steps' },
  { name: 'utensils', component: Utensils, label: 'Food / Utensils' },
  { name: 'shirt', component: Shirt, label: 'Clothes / Shirt' },
  { name: 'settings', component: Settings, label: 'Settings' },
  { name: 'calendar', component: Calendar, label: 'Calendar' },
  { name: 'inbox', component: Inbox, label: 'Inbox' },
  { name: 'target', component: Target, label: 'Goal' },
  { name: 'award', component: Award, label: 'Award' },
  { name: 'briefcase', component: Briefcase, label: 'Work' },
  { name: 'lightbulb', component: Lightbulb, label: 'Idea' },
  { name: 'compass', component: Compass, label: 'Compass' },
  { name: 'code', component: Code, label: 'Code' },
  { name: 'database', component: Database, label: 'Data' },
  { name: 'terminal', component: Terminal, label: 'Console' },
  { name: 'heart', component: Heart, label: 'Love' },
  { name: 'star', component: Star, label: 'Star' },
  { name: 'smile', component: Smile, label: 'Smile' },
  { name: 'sparkles', component: Sparkles, label: 'Sparkles' },
  { name: 'map-pin', component: MapPin, label: 'Location' },
  { name: 'mail', component: Mail, label: 'Mail' },
  { name: 'link', component: Link, label: 'Link' },
  { name: 'lock', component: Lock, label: 'Lock' },
  { name: 'bell', component: Bell, label: 'Alert' },
  { name: 'home', component: Home, label: 'Home' },
  { name: 'activity', component: Activity, label: 'Activity' },
  { name: 'bar-chart-2', component: BarChart2, label: 'Chart' },
  { name: 'check-square', component: CheckSquare, label: 'Todo' },
  { name: 'coffee', component: Coffee, label: 'Coffee' },
  { name: 'globe', component: Globe, label: 'Web' },
  { name: 'image', component: Image, label: 'Image' },
  { name: 'music', component: Music, label: 'Music' },
  { name: 'film', component: Film, label: 'Video' },
  { name: 'gift', component: Gift, label: 'Gift' },
  { name: 'sun', component: Sun, label: 'Sun' },
  { name: 'moon', component: Moon, label: 'Moon' },
  { name: 'cloud', component: Cloud, label: 'Cloud' },
  { name: 'umbrella', component: Umbrella, label: 'Weather' },
  { name: 'shopping-cart', component: ShoppingCart, label: 'Cart' },
  { name: 'tag', component: Tag, label: 'Tag' },
  { name: 'key', component: Key, label: 'Key' },
  { name: 'archive', component: Archive, label: 'Archive' },
  { name: 'rocket', component: Rocket, label: 'Launch' },
  { name: 'users-round', component: UsersRound, label: 'People' },
  { name: 'circle-check', component: CircleCheck, label: 'Completed' },
  { name: 'flag', component: Flag, label: 'Important' }
];

export const iconMap: Record<string, any> = Object.fromEntries(
  CURATED_ICONS.map(i => [i.name, i.component])
);
